"""
ECU Decision Logic Module
===========================
Implements the Electronic Control Unit (ECU) logic for the DMS.
Makes decisions based on behavioral analysis and generates alerts.
Simulates the behavior of a real ADAS ECU.
"""

import time
from typing import Optional, List, Callable
from dataclasses import dataclass, field
from enum import Enum

from src.behavioral_analysis import BehavioralMetrics, DriverState


class AlertLevel(Enum):
    """Alert severity levels."""

    NONE = 0
    INFO = 1
    WARNING = 2
    CRITICAL = 3
    EMERGENCY = 4


class AlertType(Enum):
    """Types of alerts the ECU can generate."""

    FATIGUE_WARNING = "fatigue_warning"
    FATIGUE_CRITICAL = "fatigue_critical"
    DISTRACTION_WARNING = "distraction_warning"
    DISTRACTION_CRITICAL = "distraction_critical"
    DROWSINESS_EMERGENCY = "drowsiness_emergency"
    EYES_CLOSED_LONG = "eyes_closed_long"
    SYSTEM_OK = "system_ok"
    SENSOR_ERROR = "sensor_error"


@dataclass
class Alert:
    """Represents an alert generated by the ECU."""

    alert_type: AlertType
    level: AlertLevel
    message: str
    timestamp: float
    metrics: Optional[BehavioralMetrics] = None
    acknowledged: bool = False


@dataclass
class ECUState:
    """Current state of the ECU."""

    is_active: bool = True
    current_alert_level: AlertLevel = AlertLevel.NONE
    active_alerts: List[Alert] = field(default_factory=list)
    total_alerts_generated: int = 0
    system_uptime: float = 0.0
    last_update_time: float = 0.0
    driver_state: DriverState = DriverState.UNKNOWN


class ECUDecisionEngine:
    """
    Simulates an ADAS ECU for driver monitoring.

    Implements a state machine that processes behavioral metrics
    and generates appropriate alerts based on configurable thresholds.

    The decision logic follows a hierarchical approach:
    1. Check for emergency conditions (drowsiness)
    2. Check for critical conditions (severe fatigue/distraction)
    3. Check for warning conditions (moderate fatigue/distraction)
    4. Default to normal operation
    """

    # Alert thresholds
    FATIGUE_WARNING_THRESHOLD = 0.35
    FATIGUE_CRITICAL_THRESHOLD = 0.6
    DROWSINESS_THRESHOLD = 0.75
    DISTRACTION_WARNING_THRESHOLD = 0.35
    DISTRACTION_CRITICAL_THRESHOLD = 0.6
    EYES_CLOSED_DURATION_THRESHOLD = 2.0  # seconds

    # Timing parameters
    ALERT_COOLDOWN = 5.0  # Minimum seconds between same alert type
    ESCALATION_TIME = 10.0  # Seconds before escalating unacknowledged alerts

    def __init__(self):
        """Initialize the ECU decision engine."""
        self.state = ECUState()
        self._start_time = time.time()
        self._last_alert_times: dict = {}
        self._alert_callbacks: List[Callable[[Alert], None]] = []
        self._alert_history: List[Alert] = []

    def register_alert_callback(self, callback: Callable[[Alert], None]) -> None:
        """Register a callback function to be called when an alert is generated."""
        self._alert_callbacks.append(callback)

    def process(self, metrics: BehavioralMetrics, timestamp: Optional[float] = None) -> ECUState:
        """
        Process behavioral metrics and update ECU state.

        This is the main decision loop of the ECU. It evaluates
        the current metrics against thresholds and generates
        appropriate alerts.

        Args:
            metrics: Current behavioral analysis metrics.
            timestamp: Current timestamp (defaults to time.time()).

        Returns:
            Updated ECU state.
        """
        if timestamp is None:
            timestamp = time.time()

        self.state.last_update_time = timestamp
        self.state.system_uptime = timestamp - self._start_time
        self.state.driver_state = metrics.driver_state

        # Clear expired alerts
        self._cleanup_alerts(timestamp)

        # Decision hierarchy
        if metrics.fatigue_score > self.DROWSINESS_THRESHOLD:
            self._generate_alert(
                AlertType.DROWSINESS_EMERGENCY,
                AlertLevel.EMERGENCY,
                f"EMERGENCY: Driver drowsiness detected! "
                f"Fatigue score: {metrics.fatigue_score:.2f}, "
                f"PERCLOS: {metrics.perclos:.1f}%",
                timestamp,
                metrics,
            )
        elif metrics.current_eye_closure_duration > self.EYES_CLOSED_DURATION_THRESHOLD:
            self._generate_alert(
                AlertType.EYES_CLOSED_LONG,
                AlertLevel.CRITICAL,
                f"CRITICAL: Eyes closed for "
                f"{metrics.current_eye_closure_duration:.1f}s",
                timestamp,
                metrics,
            )
        elif metrics.fatigue_score > self.FATIGUE_CRITICAL_THRESHOLD:
            self._generate_alert(
                AlertType.FATIGUE_CRITICAL,
                AlertLevel.CRITICAL,
                f"CRITICAL: High fatigue detected. "
                f"Score: {metrics.fatigue_score:.2f}",
                timestamp,
                metrics,
            )
        elif metrics.distraction_score > self.DISTRACTION_CRITICAL_THRESHOLD:
            self._generate_alert(
                AlertType.DISTRACTION_CRITICAL,
                AlertLevel.CRITICAL,
                f"CRITICAL: Driver severely distracted. "
                f"Score: {metrics.distraction_score:.2f}",
                timestamp,
                metrics,
            )
        elif metrics.fatigue_score > self.FATIGUE_WARNING_THRESHOLD:
            self._generate_alert(
                AlertType.FATIGUE_WARNING,
                AlertLevel.WARNING,
                f"WARNING: Early fatigue signs detected. "
                f"Score: {metrics.fatigue_score:.2f}",
                timestamp,
                metrics,
            )
        elif metrics.distraction_score > self.DISTRACTION_WARNING_THRESHOLD:
            self._generate_alert(
                AlertType.DISTRACTION_WARNING,
                AlertLevel.WARNING,
                f"WARNING: Driver distraction detected. "
                f"Score: {metrics.distraction_score:.2f}",
                timestamp,
                metrics,
            )
        else:
            self.state.current_alert_level = AlertLevel.NONE

        return self.state

    def _generate_alert(
        self,
        alert_type: AlertType,
        level: AlertLevel,
        message: str,
        timestamp: float,
        metrics: Optional[BehavioralMetrics] = None,
    ) -> None:
        """Generate an alert if not in cooldown."""
        last_time = self._last_alert_times.get(alert_type, 0)
        if timestamp - last_time < self.ALERT_COOLDOWN:
            return

        alert = Alert(
            alert_type=alert_type,
            level=level,
            message=message,
            timestamp=timestamp,
            metrics=metrics,
        )

        self.state.active_alerts.append(alert)
        self.state.current_alert_level = level
        self.state.total_alerts_generated += 1
        self._last_alert_times[alert_type] = timestamp
        self._alert_history.append(alert)

        # Notify callbacks
        for callback in self._alert_callbacks:
            callback(alert)

    def _cleanup_alerts(self, current_time: float, max_age: float = 30.0) -> None:
        """Remove old alerts from active list."""
        self.state.active_alerts = [
            a for a in self.state.active_alerts
            if current_time - a.timestamp < max_age
        ]

    def get_alert_history(self) -> List[Alert]:
        """Return the complete alert history."""
        return self._alert_history.copy()

    def acknowledge_alerts(self) -> int:
        """Acknowledge all active alerts. Returns count acknowledged."""
        count = 0
        for alert in self.state.active_alerts:
            if not alert.acknowledged:
                alert.acknowledged = True
                count += 1
        return count

    def reset(self) -> None:
        """Reset the ECU to initial state."""
        self.state = ECUState()
        self._start_time = time.time()
        self._last_alert_times.clear()
        self._alert_history.clear()


class ECUSimulator:
    """
    High-level ECU simulator that ties together the entire DMS pipeline.
    Provides methods for running simulation scenarios.
    """

    def __init__(self):
        self.ecu = ECUDecisionEngine()
        self._log: List[dict] = []

    def run_scenario(
        self,
        scenario_data: List[dict],
        time_step: float = 1.0 / 30.0,
    ) -> List[dict]:
        """
        Run a simulation scenario.

        Args:
            scenario_data: List of dicts with keys:
                - eyes_open (bool)
                - yaw (float)
                - pitch (float)
                - looking_forward (bool)
            time_step: Time between samples in seconds.

        Returns:
            List of result dicts for each time step.
        """
        from src.behavioral_analysis import BehavioralAnalyzer

        analyzer = BehavioralAnalyzer(window_size=60.0, sample_rate=1.0 / time_step)
        self.ecu.reset()
        results = []

        base_time = 0.0
        for i, data in enumerate(scenario_data):
            timestamp = base_time + i * time_step

            metrics = analyzer.update(
                eyes_open=data.get("eyes_open", True),
                yaw=data.get("yaw", 0.0),
                pitch=data.get("pitch", 0.0),
                looking_forward=data.get("looking_forward", True),
                timestamp=timestamp,
            )

            ecu_state = self.ecu.process(metrics, timestamp)

            result = {
                "time": timestamp,
                "eyes_open": data.get("eyes_open", True),
                "yaw": data.get("yaw", 0.0),
                "pitch": data.get("pitch", 0.0),
                "perclos": metrics.perclos,
                "fatigue_score": metrics.fatigue_score,
                "distraction_score": metrics.distraction_score,
                "driver_state": metrics.driver_state.value,
                "alert_level": ecu_state.current_alert_level.value,
                "total_alerts": ecu_state.total_alerts_generated,
            }
            results.append(result)

        return results
